### ISSUE TITLE
Extra dict is always null for CityScapes while loading the dataset

### ISSUE THREAD

**Issue by shub-kris** [charlesCXK/TorchSemiSeg#10]
Hi, I tried to runt he code here and https://github.com/charlesCXK/TorchSemiSeg/blob/9c569391e99e8bbc6894f2ed65435cc8451e56e6/exp.city/city8.res50v3%2B.CPS%2BCutMix/dataloader.py#L172 here, the extra dict will always be None as the TrainPre() here https://github.com/charlesCXK/TorchSemiSeg/blob/9c569391e99e8bbc6894f2ed65435cc8451e56e6/exp.city/city8.res50v3%2B.CPS%2BCutMix/dataloader.py#L82 always returns an empty extra_dict and hence batches won't have the key 'img'

**Comment by shub-kris** [comment]
@charlesCXK ?

**Comment by charlesCXK** [comment]
Hi, sorry for the late reply.
In fact, the key 'img' is not used during training. We use key 'data' instead: https://github.com/charlesCXK/TorchSemiSeg/blob/9c569391e99e8bbc6894f2ed65435cc8451e56e6/exp.city/city8.res50v3%2B.CPS%2BCutMix/dataloader.py#L180

**Comment by shub-kris** [comment]
Thanks  :) for the clarification. I should have noticed before.
