### ISSUE TITLE
Other SOTA semi-supervised segmentation methods

### ISSUE THREAD

**Issue by KarelZhang** [charlesCXK/TorchSemiSeg#11]
Hi,could you give a date when you can release other SOTA semi-supervised segmentation methods?

**Comment by charlesCXK** [comment]
Hi, thanks for your attention. I am working on other projects these days so the open-source process was delayed. I feel sorry for that. I will update those methods ASAP.

**Comment by KarelZhang** [comment]
Ok, very much looking forward to it！

**Comment by charlesCXK** [comment]
@KarelZhang 
Hi, we have released the code of Mean Teacher, CCT, and GCT. Please check them.

**Comment by KarelZhang** [comment]
> @KarelZhang
> Hi, we have released the code of Mean Teacher, CCT, and GCT. Please check them.

OK, so great! Thanks!
