### ISSUE TITLE
issue for memory and time usage

### ISSUE THREAD

**Issue by lisyuan-zhu** [charlesCXK/TorchSemiSeg#12]
May I ask how much memory and time for the VOC dataset? I use the script with 1/8 data partitions, and needs nearly 64g GPU memory. Is it normal? Thank you for your help.

**Comment by charlesCXK** [comment]
Hi,
batch_size = 2 needs ~8500MiB GPU memory.

**Comment by lisyuan-zhu** [comment]
Thanks a lot. It seems that I can't afford this great algorithm in best performance, lol.
