### ISSUE TITLE
configs for resnet101 

### ISSUE THREAD

**Issue by dyh127** [charlesCXK/TorchSemiSeg#13]
Hi, 

Thank you for the sharing and excellent work. I have run the code for resnet50 but I fail to find the configs for resnet101, would you like to share them? 

Besides, I notice there are some tiny changes in the resnet50 and ASPP. Is there any reason?  and how to get the pre-trained model trained on ImageNet? (I mean using standard supervised learning or self-supervised learning?) 

Besides, I try to download the city.zip and unzip it. But I fail to unzip it. So would you like to have a check?

By the way, thank you for your code, it is very helpful.

Best regards,
Yuhang

**Comment by charlesCXK** [comment]
Hi, Yuhang:
1. For ResNet-101, hyper-parameters need no change.
2. We use ResNet_v1c, where the first 7x7 convolution layer in the initial ResNet is replaced with several smaller convolutions. You could find the pre-trained weights using 'v1c'.
3. Maybe the file is not complete after downloading (e.g., unexpected broken). I will also check the remote file.

**Comment by dyh127** [comment]
Thank you so much! Please check the city.zip since I have downloaded it twice but none of them can be unzipped.

**Comment by charlesCXK** [comment]
Hi, I have downloaded the remote file. It is fine.
