### ISSUE TITLE
Reproduce your Resnet-101 result

### ISSUE THREAD

**Issue by pyedog1976** [charlesCXK/TorchSemiSeg#15]
Thanks for your share! Great works!

I'm trying to reproduce your result based on resnet-101 under the PascalVOC dataset. 
I miss your config files of the resnet-101, and I'm wondering is there any change compared with your resnet-50 settings (in [here](https://github.com/charlesCXK/TorchSemiSeg/blob/main/exp.voc/voc8.res50v3%2B.CPS%2BCutMix/config.py))? 

Cheers

**Comment by charlesCXK** [comment]
Hi, the hyper-parameters have no need to change.
