### ISSUE TITLE
About different initialization?

### ISSUE THREAD

**Issue by Luoxd1996** [charlesCXK/TorchSemiSeg#16]
Hi, Xiaokang,
Congrats so solid work. I have a question about the different initialization, I check the code of the segmentation model, but I don't find the operation of parameters initialization, I want to know the details of this operation, could you give me some advice?
Best,
Xiangde.

**Comment by charlesCXK** [comment]
Hi, weight initialization is here: https://github.com/charlesCXK/TorchSemiSeg/blob/0c10bf0b39924b804a0bf76ca6490123bfbb02a6/exp.voc/voc8.res50v3%2B.CPS/train.py#L84

**Comment by Luoxd1996** [comment]
Hi, Xiaokang,
Thanks for your so quick reply. My concerns have been solved, thanks!!!
Best,
Xiangde.
