### ISSUE TITLE
Ahout the cps loss on labeled data?

### ISSUE THREAD

**Issue by pkuCactus** [charlesCXK/TorchSemiSeg#18]
Hi, @charlesCXK ,

Great work and thanks for the share of the code.
I have a question that the cps loss in the paper is also computed on the labeled data, but can't find in the code.  Is it forgot or the code is not complete. 

Best regards.

**Comment by charlesCXK** [comment]
Hi, we compute CPS loss (w/o CutMix) on the labeled/unlabeled data [here](https://github.com/charlesCXK/TorchSemiSeg/blob/bab3a31ef7a5b59b932820b4d5d93a1b8bfc41ec/exp.voc/voc8.res50v3%2B.CPS/train.py#L185). For CPS w/ CutMix, we only compute it on unlabeled data.

**Comment by pkuCactus** [comment]
I see, thanks for your reply.
