### ISSUE TITLE
overlap in you supervised and unsupervised data-set, for few supervision data

### ISSUE THREAD

**Issue by Sun-Rider** [charlesCXK/TorchSemiSeg#20]
In you few-supervise setting, which is in [here](https://github.com/charlesCXK/TorchSemiSeg/blob/bab3a31ef7a5b59b932820b4d5d93a1b8bfc41ec/DATA/pascal_voc/subset_train_aug/pseudoseg_labeled_1-16.txt#L92) which seems is labeled data but over lap with [here](https://github.com/charlesCXK/TorchSemiSeg/blob/bab3a31ef7a5b59b932820b4d5d93a1b8bfc41ec/DATA/pascal_voc/subset_train_aug/pseudoseg_unlabeled_1-16.txt#L497).

Also, 
in you 1/8 ratio,  [labeled](https://github.com/charlesCXK/TorchSemiSeg/blob/bab3a31ef7a5b59b932820b4d5d93a1b8bfc41ec/DATA/pascal_voc/subset_train_aug/pseudoseg_labeled_1-8.txt#L183) with [unlabeled](https://github.com/charlesCXK/TorchSemiSeg/blob/bab3a31ef7a5b59b932820b4d5d93a1b8bfc41ec/DATA/pascal_voc/subset_train_aug/pseudoseg_unlabeled_1-8.txt#L608)

in you 1/4 ratio, [labeled](https://github.com/charlesCXK/TorchSemiSeg/blob/bab3a31ef7a5b59b932820b4d5d93a1b8bfc41ec/DATA/pascal_voc/subset_train_aug/pseudoseg_labeled_1-4.txt#L366) with [unlabeled](https://github.com/charlesCXK/TorchSemiSeg/blob/bab3a31ef7a5b59b932820b4d5d93a1b8bfc41ec/DATA/pascal_voc/subset_train_aug/pseudoseg_unlabeled_1-4.txt#L1),

in you 1/2 ratio, https://github.com/charlesCXK/TorchSemiSeg/blob/bab3a31ef7a5b59b932820b4d5d93a1b8bfc41ec/DATA/pascal_voc/subset_train_aug/pseudoseg_labeled_1-2.txt#L732 and https://github.com/charlesCXK/TorchSemiSeg/blob/bab3a31ef7a5b59b932820b4d5d93a1b8bfc41ec/DATA/pascal_voc/subset_train_aug/pseudoseg_unlabeled_1-2.txt#L321.

In each ratio, there is one overlap, and I suspect it should be a mis-operation.

**Comment by Sun-Rider** [comment]
Sorry, it shouldn't be a big deal. As the overlapped data is counted as supervised part.
It just confused me a bit, all good.

**Comment by charlesCXK** [comment]
@Sun-Rider Hi, I understand what you are worrying about. However, the unlabeled text ids (e.g., pseudoseg_unlabeled_1-2.txt) is not used in our experiments. We follow [PseudoSeg](https://github.com/googleinterns/wss) and view the whole augmented set of VOC as the unlabeled set.

**Comment by Sun-Rider** [comment]
@charlesCXK  Thanks so much for the clarification, that makes more sense.
