### ISSUE TITLE
Difference between code and paper

### ISSUE THREAD

**Issue by Vicvolda** [charlesCXK/TorchSemiSeg#25]
Hi, first, thanks for sharing for this great work !
I was reading the paper and the code and I notice in the Mean Teacher exp, the paper said you use x1 and x2 with two different augmentations, but in the code you simply use x to feed the teacher and the student ? Is it normal or did I miss something ?
Moreover, could you release the mean teacher experience for cityscapes ? Because I could not reproduce the results from the paper 

Thanks

**Comment by charlesCXK** [comment]
Hi, [GCT](https://github.com/ZHKKKe/PixelSSL) finds that using x1 and x2 for mean teacher has no benefit on the performance, thus we follow them and use x as input only.

For MeanTeacher on Cityscapes, the `unsup_weight` is 100, too. The supervised loss is OHEM, which is different from that of VOC.
