### ISSUE TITLE
Parameter Settings at different scales

### ISSUE THREAD

**Issue by xyf159** [charlesCXK/TorchSemiSeg#28]
Hi,is the learning rate of 1/16 also 0.0025?
I can't achieve the accuracy in the paper by using 0.0025.

**Comment by charlesCXK** [comment]
Hi, which experiment do you mean?

**Comment by xyf159** [comment]
CPS+cutmix  
I achieved the accuracy of the paper at the setting of 1/8。

**Comment by charlesCXK** [comment]
Hi, the learning rate is the same for all the experiments on VOC.

**Comment by xyf159** [comment]
CPS+cutmix on VOC , batch_size 8 , lr 0.0025, cps_weight 1 ,miou 70.2

**Comment by charlesCXK** [comment]
I can’t tell where the problem is with such limited information. Have you tried to run the experiment several times? Also, could you reproduce the result of `CPS+CutMix, ResNet-101` on the 1/16 split?

**Comment by xyf159** [comment]
I have conducted two experiments. At present, all my experiments are on resnet-50, and then I will conduct experiments on resnet-101. Thank you for your reply. I will try several times more.
