### ISSUE TITLE
Weight decay difference between paper and config

### ISSUE THREAD

**Issue by JihwanEom** [charlesCXK/TorchSemiSeg#29]
Hi, thank you for releasing awesome work!

I have a question about weight decay value config on resnet50 - pascal voc - 1/8 labels.

The paper said "The momentum is fixed as 0.9 and the weight decay is set to **0.0005(5e-4)**"

But in config file, **the weight decay value defined with 1e-4**.
"""
In TorchSemiSeg/exp.voc/voc8.res50v3+2B.CPS+2BCutMix/config.py ...
line 106: C.weight_decay = 1e-4
"""

Which value should I follow? Thank you!

**Comment by charlesCXK** [comment]
Hi, we use weight_decay = 1e-4 in our experiments. The number in the paper is a typo.
We also run experiments using weight_decay = 5e-4, the result is ~73.0% for `voc8.res50v3+.CPS`, so it will not influence the performance a lot.

**Comment by JihwanEom** [comment]
Noted. I'll close this issue.
