### ISSUE TITLE
Corrupted Citiscapes archive

### ISSUE THREAD

**Issue by DominikFilipiak** [charlesCXK/TorchSemiSeg#31]
The Citiscapes archive from OneDrive seems to be corrupted. I've tested it on two devices and still can't unpack it.
```console
$ unzip city.zip 
Archive:  city.zip
warning [city.zip]:  8575179524 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [city.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```

**Comment by charlesCXK** [comment]
@DominikFilipiak 
Hi, I have downloaded the file again and try to unzip it. 
I find that if I use the command `unzip` I will get the same error as you. However, if I unzip it by right-clicking on this file in Windows, and then selecting "unzip all", the process is normal. Please try this method.

**Comment by charlesCXK** [comment]
Hi, please try to use`city.tar` in that directory.
