### ISSUE TITLE
Other SOTA methods on Cityscapes

### ISSUE THREAD

**Issue by jfzhuang** [charlesCXK/TorchSemiSeg#33]
Hi, first, thanks for sharing for this great work !
I noticed that you have released other SOTA methods on the VOC dataset. I wonder if you will release them on the Cityscapes dataset?

Thanks

**Comment by charlesCXK** [comment]
Hi, given the code of these SOTA methods on VOC, they could be easily implemented on Cityscapes as well. Just keep hyper-parameters the same as that of VOC.

**Comment by jfzhuang** [comment]
Thanks for your reply.
