### ISSUE TITLE
Overlap ratio meaning

### ISSUE THREAD

**Issue by TopTea1** [charlesCXK/TorchSemiSeg#37]
Hi, I have a question about the Figure 7 of the paper. What is the formula to obtain the overlap ratio? Is it an mIoU between the predictions of network 1 and network 2  for each kind of samples ?

Thanks

**Comment by charlesCXK** [comment]
Hi, this figure uses the precision metric, not mIoU,

**Comment by TopTea1** [comment]
Thanks for the clarification and your quick answer !
