### ISSUE TITLE
Getting TypeError on running script.sh

### ISSUE THREAD

**Issue by sakthi-prasath** [charlesCXK/TorchSemiSeg#44]
I am getting this error on running script.sh for exp.voc/voc8.res50v3+.CPS :

![image](https://user-images.githubusercontent.com/63360785/139559369-a3adb9a9-a07b-44db-8875-095c815668ee.png)

I have checked all the variables and paths specified and they seem to be right. Any idea what is wrong here?

**Comment by charlesCXK** [comment]
Hi, it seems that the variable `img` is empty. Please print it out in the console to check it.
