### ISSUE TITLE
Stop Gradient

### ISSUE THREAD

**Issue by jcwang123** [charlesCXK/TorchSemiSeg#45]
We notice that in the manuscript, Y should not backward the gradients.
But in the codes, there are no operation to stop the gradients?

**Comment by hetranger** [comment]
`_,  pred = torch.max(output, dim=1)` is equivalent to `pred = torch.argmax(output, dim=1)`, which has no gradient backpropagated.

**Comment by jcwang123** [comment]
thanks!
