### ISSUE TITLE
Training process stops after few epochs

### ISSUE THREAD

**Issue by phuocnguyen2008** [charlesCXK/TorchSemiSeg#47]
First of all, thank you for your great work.
Currently, I'm using your code to train on another dataset and face the problem described in the attached image. 
After install APEX successfully, I run training code with 2 A6000 GPUs and it stops after few epochs.
Another problem I want to ask is that my server keeps restarting when I ran the training code for several times before I could. Do you know the reason why?
Thank you very much
![image](https://user-images.githubusercontent.com/34409468/141223748-68e3e522-8304-49ee-bcbf-30343a39eb56.png)

**Comment by ChrisLiang2020** [comment]
@phuocnguyen2008 I'm sorry to bother you. Do you run programs on Windows system? I have some problems installing apex on windows.

**Comment by phuocnguyen2008** [comment]
@ChrisLiang2020 I do not run on Windows.
