### ISSUE TITLE
how to train model with custom data?

### ISSUE THREAD

**Issue by wuyunxiangwyx** [charlesCXK/TorchSemiSeg#49]
Thank you for your job! I want to know how to train cps with my custom dataset, i should change code where it is?

**Comment by charlesCXK** [comment]
Hi, just change the Dataset Class such as [here](https://github.com/charlesCXK/TorchSemiSeg/blob/42c1a851aa12e6e7a22398ee4191cf40a588ed6e/exp.voc/voc8.res50v3%2B.CCT/dataloader.py#L105), and change something related to your dataset in the [config file](https://github.com/charlesCXK/TorchSemiSeg/blob/42c1a851aa12e6e7a22398ee4191cf40a588ed6e/exp.voc/voc8.res50v3%2B.CCT/config.py#L83).
