### ISSUE TITLE
Parameter Initialization for Mean Teacher

### ISSUE THREAD

**Issue by ldkong1205** [charlesCXK/TorchSemiSeg#50]
Thanks for sharing this excellent work!

I have a question for the parameter initialization in this Teacher-Student paradigm:

- At the very beginning of training, the parameters for the Teacher net are initialized by that of the Student net, as in https://github.com/charlesCXK/TorchSemiSeg/blob/main/exp.voc/voc8.res50v3%2B.MeanTeacher/network.py#L30.
- Under this case, will the copy destroy the original setting? The parameters (of the semantic segmentation head) for the Teacher and Student are initialized differently as you said, but they are now unified by `param_t.data.copy_(param_s.data)`.

Looking forward to your clarification! Thank you

**Comment by charlesCXK** [comment]
Hi, the segmentation head of two networks in CPS are initialized differently. 
In Mean Teacher, the teacher and student network are just the same (including the segmentation head) at the very beginning.

**Comment by ldkong1205** [comment]
Thank you for your reply!

I would also like to ask about the weight parameter for the CPS loss. I tried your method on another dataset and it turns out that this weight parameter plays a very important role in the final scores (e.g., it might vary more than 10% mIoU). Is this normal? Any suggestion for selecting the best possible weight parameter?

**Comment by charlesCXK** [comment]
Yes, the weight for CPS loss is very important. Please see Figure 4 in our [paper](https://arxiv.org/pdf/2106.01226.pdf) for ablations on the CPS weight. 
When I conducted experiments, I tried to make the re-weighted CPS loss has a similar value to the loss on the labeled data. You could try more weights around that weight according to the final performance.

**Comment by ldkong1205** [comment]
Got it. Thanks for the suggestion!

**Comment by JihwanEom** [comment]
Hi, @charlesCXK.

I wonder about the comment you said "I tried to make the re-weighted CPS loss has a similar value to the loss on the labeled data.".

Intuitively, I presumed what you tended but I want to know theoretical reason for this. 

Is there any paper about the magnitude of unsupervised loss?

Thank you.
Jihwan
