### ISSUE TITLE
Program stuck on startup

### ISSUE THREAD

**Issue by MLuminous** [charlesCXK/TorchSemiSeg#52]
**After the environment is set up, I use only one GPU GeForce RTX 3080 to run the script.sh in the startup manual, and I find that the program will be stuck on this page for more than ten minute：**
![1](https://user-images.githubusercontent.com/32741409/158018919-ebeb3f04-b5b9-4895-b933-bb1c0d7bbfc8.jpg)

and Then the program reports an error
![F083F58B589603D5EB7A5690F4FA935C](https://user-images.githubusercontent.com/32741409/158018994-dd7eb03e-d5bd-46dc-9450-88a648ab4e23.jpg)
I don't know why this happens, can you help me bro?

**Comment by ChrisLiang2020** [comment]
@MLuminous I'm sorry to bother you. Have you successfully run the program now? Is it a program running on windows?

**Comment by liyueyuan-alice** [comment]
@MLuminous @charlesCXK @ChrisLiang2020 I'm sorry to bother you, has this problem been resolved? I also encountered an error similar to yours. I need your help, thanks.
