### ISSUE TITLE
could I know use 4Tesla V100 GPUs to train the model will spend how many hours?

### ISSUE THREAD

**Issue by Joe-Tony-Joe** [charlesCXK/TorchSemiSeg#56]

**Comment by charlesCXK** [comment]
Please check the [log](https://pkueducn-my.sharepoint.com/personal/pkucxk_pku_edu_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fpkucxk%5Fpku%5Fedu%5Fcn%2FDocuments%2FProject%2FCVPR2021%2DCPS%2FTraining%20Log%20and%20Checkpoint%2Fvoc8%2Eres50v3%2B%2ECPS%2Flog%5Fvoc8%2Eres50v3%2B%2ECPS%2Etxt&parent=%2Fpersonal%2Fpkucxk%5Fpku%5Fedu%5Fcn%2FDocuments%2FProject%2FCVPR2021%2DCPS%2FTraining%20Log%20and%20Checkpoint%2Fvoc8%2Eres50v3%2B%2ECPS&ga=1). It takes about 7 hours for Res50 1/8 split.
