### ISSUE TITLE
when I run eval.py, the program rapidly finish and the result show nothing. It is seems because the azureml.core, but I do not know how to solve it. Could you give me some suggestion?

### ISSUE THREAD

**Issue by Joe-Tony-Joe** [charlesCXK/TorchSemiSeg#59]
21 14:56:49 WRN Failure while loading azureml_run_type_providers. Failed to load entrypoint azureml.scriptrun = azureml.core.script_run:ScriptRun._from_run_dto with exception (cryptography 2.4.1 (/root/miniconda3/envs/semiseg/lib/python3.6/site-packages), Requirement.parse('cryptography>=2.5'), {'paramiko'}).
21 14:56:49 Could not load the run context. Logging offline
21 14:56:50 using devices 0
epoch-5.pth

**Comment by charlesCXK** [comment]
Hi, we didn't use Azure service in this codebase. 
Please set some breakpoints in `eval.py` and see what happened.

**Comment by Joe-Tony-Joe** [comment]
thank you! I have solved it and I found it because of my parameter in eval.py is set by false
