### ISSUE TITLE
Self-training Details

### ISSUE THREAD

**Issue by Sun-Rider** [charlesCXK/TorchSemiSeg#6]
Hi,

Thanks so much for the share! I'm also very enjoy to read your paper!
 
I just miss the code of the self-training, in your Table 7.  Could you please provide some details about it? 

Cheers!

**Comment by charlesCXK** [comment]
Hi, we haven't released other SOTA methods yet. However, for self-training, you could try yourself first. It is simple and only has three steps:
```
1. Train a full-supervised model on the labeled set and save the model.
2. Use the saved checkpoint to generate the one-hot pseudo labels for the unlabeled set.
3. Use the pseudo labels from unlabeled set and ground truth from labeled set to train a new model. It is just like training a fully-supervised model on the full dataset.
```

**Comment by Sun-Rider** [comment]
Thanks for the comment.
