### ISSUE TITLE
questions about the results

### ISSUE THREAD

**Issue by ruichen0319** [charlesCXK/TorchSemiSeg#63]
Hi! I want to know that how do you get the result.
 For Pascal VOC 2012，labeled ratio is 1/8，epochs is 34，Performing it for three times and getting the average of the last epoch i.e 33 epoch OR   Performing it only once and getting the max result of 20 epoch to 33 epoch ?

**Comment by charlesCXK** [comment]
Hi, we select the best checkpoint (e.g., 20-epoch in your case) to get the result.

**Comment by ruichen0319** [comment]
> 嗨，我们选择最好的检查点（例如，在您的情况下为20 epoch）以获得结果。

**Comment by ruichen0319** [comment]
If  I use 20-33 epoch to eval ,the MIOU of 20-epoch is 73.6 and the MIOU of 33-epoch is 72.0,now the performance should be 73.6,right?

**Comment by charlesCXK** [comment]
yes.

**Comment by ruichen0319** [comment]
Get it!Thanks a lot for your quick respond
