### ISSUE TITLE
About the batchsize with CutMIx on CItyscapes 

### ISSUE THREAD

**Issue by JoyHuYY1412** [charlesCXK/TorchSemiSeg#65]
Hi, thank you for your work. I have a question about the CuTMIx.

When setting the batch size to 16 for Cityscapes as in your original paper, since using 8GPUs (conventional setting), the batch size for each GPU is 1.

I wonder how to perform CutMix when only one unlabeled image is in a GPU? Can you give me some advice? Or did I misunderstand the batch size part?

Appreciate your reply!

**Comment by charlesCXK** [comment]
Hi, we use two dataloaders for unlabeled images: https://github.com/charlesCXK/TorchSemiSeg/blob/f67b37362ad019570fe48c5884187ea85f2cc045/exp.voc/voc8.res50v3%2B.CPS%2BCutMix/train.py#L83
