### ISSUE TITLE
code running error

### ISSUE THREAD

**Issue by lily-wei0211** [charlesCXK/TorchSemiSeg#66]
When  I train CPS on cityscapes , the code reports errors and interrupts from time to time.
Did this happen to you? how to solve? Thanks
The error is as follows:

![微信图片_20220819152849](https://user-images.githubusercontent.com/58206598/185568188-659e5408-1d55-4a9e-969d-b2c91c46a86a.png)

![微信图片_20220819152856](https://user-images.githubusercontent.com/58206598/185568216-a188f4de-bd64-499e-8158-4cfcd04f20aa.png)

**Comment by charlesCXK** [comment]
Hi, It seems that the problem is related to the communication of the machine you are using, not the code.
