### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by ruichen0319** [charlesCXK/TorchSemiSeg#67]
![image](https://user-images.githubusercontent.com/95664687/186563681-192064f9-c680-4344-8786-5fccc458b263.png)
When I use your docker to train,the error occured,it is likely that the version of cuda driver is too low.But my cuda driver is 465.19.01,which is supported CUDA11.3,the cuda in the docker is only 10.1,it is compatible,right?I don't why,can you help me?I will appreciative. 
![image](https://user-images.githubusercontent.com/95664687/186563919-75024b83-ba1b-4566-88f5-8b945406dd20.png)
![image](https://user-images.githubusercontent.com/95664687/186564132-4f8d7ff8-3f49-44ff-b008-664ca80beb01.png)

**Comment by charlesCXK** [comment]
Hi, the docker is based on Cuda 10.1. It is recommended to install Apex in your machine manually.
