### ISSUE TITLE
Questions about CPS loss.

### ISSUE THREAD

**Issue by kinux98** [charlesCXK/TorchSemiSeg#79]
Hi. 

First of all, thanks for sharing this great work!

Q1. What is the purpose of applying cps loss on labeled data even though they have ground-truth? 

Q2. As already questioned at https://github.com/charlesCXK/TorchSemiSeg/issues/43#issuecomment-1110630033, I have a similar issue: when I remove CPS loss during the training, the performance is higher than when it is used. It seems that CPS loss does not contribute to performance improvement. Have you figured it out?

**Comment by nysp78** [comment]
Hello, 
I have encountered a similar issue concerning the cps loss.

**Comment by daeunni** [comment]
@kinux98  Hi, I encountered the same issue. 
how did you deal with that problem? What do you think about CPS loss?
