### ISSUE TITLE
issue about the random seed

### ISSUE THREAD

**Issue by wener-yung** [charlesCXK/TorchSemiSeg#8]
Hi,
Thanks for the excellent work. There is the problem, I run the code reveral times, and each time the loss is different. Are there any random seeds haven't been fixed.
`seed = config.seed
    if engine.distributed:
        seed = engine.local_rank
    torch.manual_seed(seed)
    random.seed(seed)
    np.random.seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)`

**Comment by charlesCXK** [comment]
Hi, the upsample operation in PyTorch is non-deterministic, which means even if all the seeds are set, the results are still different.
