### ISSUE TITLE
Image present in both labeled and unlabeled splits

### ISSUE THREAD

**Issue by rvandeghen** [charlesCXK/TorchSemiSeg#80]
Hi,

I wanted to use the splits you provide to train my model. However, I found that there are images that are present in both labeled and unlabeled files. Is it something that you are aware of ?

Renaud

**Comment by charlesCXK** [comment]
Hello, this should not happen. Can you provide the split and the image id?
When generating the split, I used images other than labeled images as unlabeled.

**Comment by rvandeghen** [comment]
@charlesCXK The concerned splits are pseudoseg_labeled_1-16 and pseudoseg_unlabeled_1-16, with the image id 2008_004822.
