### ISSUE TITLE
Memory and Inf time (fps) for CPS

### ISSUE THREAD

**Issue by JoyHuYY1412** [charlesCXK/TorchSemiSeg#81]
Hi Xiaokang,

Thank you for your great work! 
Would you mind providing me with the memory and inf time for CPS? It would help a lot for citing your work.  
I appreciate your help.

**Comment by JoyHuYY1412** [comment]
I think the memory is not just the number of trainable parameters as you used cutmix, which actually doubled the batch_size when feeding them into the network.

**Comment by charlesCXK** [comment]
Hi, we didn't count these numbers. But I agree with what you said, memory should be the situation of GPU memory usage during training, not the number of parameters.
