### ISSUE TITLE
About pretrained weights

### ISSUE THREAD

**Issue by chau25102001** [charlesCXK/TorchSemiSeg#83]
Firstly, thanks for the great work!

I notice that you provide only pretrained weights for resnet50 and resnet101. My question is are those weights pretrained on segmentation tasks (maybe on cityscapes?) or are they pretrained on ImageNet? Also, are other network pretrained weights (resnet18 for example) available, if so would you mind share them?

Thanks in advance!

**Comment by charlesCXK** [comment]
Hi, the pretrained weights of ResNet are only trained on ImageNet.
I haven't conducted experiments on ResNet-18, but you could download it from [here](https://drive.google.com/file/d/1PP7mEMvqW6vBMDeNhrS6l13RU5TwI6cA/view?usp=sharing).
The ResNet-18 link comes from [TorchSeg](https://github.com/ycszen/TorchSeg).
