### ISSUE TITLE
Download the data (VOC, Cityscapes) and pre-trained models from [OneDrive link] is not found

### ISSUE THREAD

**Issue by yjq767579182** [charlesCXK/TorchSemiSeg#85]
Download the data (VOC, Cityscapes) and pre-trained models from [OneDrive link] is not found

**Comment by KKaiYH** [comment]
I have also encountered this problem

**Comment by charlesCXK** [comment]
Sorry, there is a little problem with my OneDrive account. I have updated the links. @yjq767579182 @KKaiYH

**Comment by yjq767579182** [comment]
thank you very much

**Comment by yjq767579182** [comment]
I hope this email finds you well. I am writing to inform you about an issue I encountered with the data dataset that was provided.

Upon attempting to access the data dataset, I discovered that it appears to be corrupt or damaged. Unfortunately, this prevents me from properly utilizing the dataset for my current project. I have made several attempts to extract and utilize the data, but all of them have been unsuccessful.



yaojiaqi
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "charlesCXK/TorchSemiSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月21日(星期天) 晚上10:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [charlesCXK/TorchSemiSeg] Download the data (VOC, Cityscapes) and pre-trained models from [OneDrive link] is not found (Issue #85)





 
Closed #85 as completed.

**Comment by charlesCXK** [comment]
Since 2021, I haven't made any modifications to the data. Could it be due to network issues? @yjq767579182
