### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by RzzzLiu** [charlesCXK/TorchSemiSeg#87]
Hello, I have run your program. The codes' positions seem a little different with the document of your "Getting Started", so to address the problem of importing the modules in the furnace directory I move the codes in the directory "/TorchSemiSeg-main/exp.city/city8.res50v3+.CPS+CutMix" into the furnace directory. and we got the result below, it seems no bugs but appears no results at all, so I cannot figure out what the mistakes are. Could you please help me with the problem?
![image](https://github.com/charlesCXK/TorchSemiSeg/assets/87182943/c8181e58-f639-4a70-abef-edb0016322ea)

**Comment by LeonSakura** [comment]
我也遇到了这个问题，请问您解决了吗

**Comment by RzzzLiu** [comment]
需要将环境全部按照接近作者给出的文件进行配置，我用CUDA10.0和python3.7的基础环境，加上作者文件里给出的需要用pip安装的组件版本，可以跑了
