### ISSUE TITLE
Hi, how should I test your pretrained model?

### ISSUE THREAD

**Issue by KarelZhang** [charlesCXK/TorchSemiSeg#9]

**Comment by charlesCXK** [comment]
Hi, we didn't release pre-trained models. You could train a model following the instructions.

**Comment by KarelZhang** [comment]
ok，got it，thanks！

**Comment by Joe-Tony-Joe** [comment]
> ok，got it，thanks！

Hi， brother. Do you gain the model, if you trained it, could you please send me a copy of your model?
